"""add kCC

Revision ID: 578b197dee40
Revises: 31187f23d488
Create Date: 2025-02-20 07:15:25.161269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578b197dee40'
down_revision = '31187f23d488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kcc_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sessions_per_month', sa.Integer(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kcc_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('applied_discount', sa.Integer(), nullable=True),
    sa.Column('recurring_payment_date', sa.Integer(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['kcc_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kcc_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['kcc_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kcc_booking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['kcc_bookings.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['kcc_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kcc_booking_sessions')
    op.drop_table('kcc_schedules')
    op.drop_table('kcc_bookings')
    op.drop_table('kcc_packages')
    # ### end Alembic commands ###
