"""add notes colomn asaboking

Revision ID: 746c8a706b34
Revises: 63cb2802e810
Create Date: 2025-02-07 15:40:55.558547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746c8a706b34'
down_revision = '63cb2802e810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asa_booking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asa_booking_sessions', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
