"""add user profile details

Revision ID: 7b9de629008f
Revises: e4d9696e9586
Create Date: 2025-03-02 04:55:13.022278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9de629008f'
down_revision = 'e4d9696e9586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mobile_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('school')
        batch_op.drop_column('mobile_phone')
        batch_op.drop_column('address')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
