"""add presence status

Revision ID: 97f3d520dafa
Revises: 4dcc6ce4ca3b
Create Date: 2025-02-04 15:14:06.295859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f3d520dafa'
down_revision = '4dcc6ce4ca3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presence_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('presence_status')

    # ### end Alembic commands ###
