"""add coupung

Revision ID: dd9eff241ca9
Revises: 97acac69dc2d
Create Date: 2025-01-08 06:07:58.522118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd9eff241ca9'
down_revision = '97acac69dc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asa_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_discount', sa.Integer(), nullable=True))

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Integer(), nullable=False))
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('discount_amount')

    with op.batch_alter_table('asa_bookings', schema=None) as batch_op:
        batch_op.drop_column('applied_discount')

    # ### end Alembic commands ###
