"""add price base

Revision ID: f1ec9c40e594
Revises: f2904380aa24
Create Date: 2025-01-05 12:05:49.341001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ec9c40e594'
down_revision = 'f2904380aa24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('daily_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('daily_price')
        batch_op.drop_column('monthly_price')

    op.drop_table('coupon')
    # ### end Alembic commands ###
