"""add is trial sesscion

Revision ID: fdb0240bc5c3
Revises: 9f85ee6ba60b
Create Date: 2025-02-04 11:41:51.049308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb0240bc5c3'
down_revision = '9f85ee6ba60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asa_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asa_packages', schema=None) as batch_op:
        batch_op.drop_column('is_trial')

    # ### end Alembic commands ###
